# tonicdb is the postgres database that will hold information about your workspace.
tonicdb:
  host: <db-host>
  port: 5432
  dbName: tonic
  user: <user>
  password: <password>
  sslMode: Require

environmentName: <company-name>

# tonicStatisticsSeed will cause generations to be consisent with each other for anything where consistency is set to true.
# otherwise each generation will be internally consistent, but not consistent with other generations. Uncomment and set to any integer to enable.
# tonicStatisticsSeed: <any-integer>

# numberOfWorkers will determine how many worker containers are deployed when installing the helm chart.
numberOfWorkers: 1

# enableLogCollection will send errors and general information about generations to Tonic if true. It will not send user data.
enableLogCollection: false

# enableSparkSupport will install the necessary additional components to allow Tonic to connect to your Spark instance
# enableSparkSupport: true

# This value will be provided to you by Tonic and will allow you to authenticate against our private docker repository.
dockerConfigAuth: <docker-config-auth>

# You can set this to a specific Tonic version number if you wish to ensure you always get the same version. Otherwise you will always deploy the latest version of Tonic.
tonicVersion: latest

# container repository with tonic images. If you don't use the default one you will have to copy images over before deployment
tonic:
  notifications:
    image: quay.io/tonicai/tonic_notifications
  pii_detection:
    image: quay.io/tonicai/tonic_pii_detection
  spark_helper:
    image: quay.io/tonicai/tonic_spark_helper
  web_server:
    image: quay.io/tonicai/tonic_web_server
  worker:
    image: quay.io/tonicai/tonic_worker

# Use a Tonic license to enable different enterprise features. License keys can be obtained from Tonic.
# tonicLicense: <license-key>

# Below are the settings for Single Sign On. Not every provider requires every value. The Tonic support team will help you configure this.
# tonicSsoConfig:
#   provider: <provider-name>
#   domain: <sso-domain>
#   clientId: <client-id>
#   clientSecret: <client-secret>
#   identityProviderId: <identity-provider-id>
#   authServerId: <auth-server-id>
#   groupFilter: .*Tonic.*

# Configuration options for tonic-notifications
# tonicSmtpConfig:
#   tonicUrl: <tonic URL, for links>
#   sendingAddress: <notifications@yourdomain.com>
#   smtpServerAddress: <smtp host>
#   smtpServerPort: <smtp port>
#   smtpUsername: <smtp username>
#   smtpPassword: <smtp password>


# Role used by Tonic to connect to AWS Lambda. This is needed for Snowflake and Redshift integrations.
# awsLambdaRoleArn: arn:aws:iam::<accountId>:role/<role-name>