{{ $image := "" }}
{{- if ((.Values.tonicai).pyml_service).image }}
{{- $image = .Values.tonicai.pyml_service.image }}
{{- else }}
  {{- $image = "quay.io/tonicai/tonic_pyml_service" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-pyml-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: tonic-pyml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-pyml-service
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-pyml-service
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
      - securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        env:
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
        image: {{ $image }}:{{ .Values.tonicVersion }}
        imagePullPolicy: Always
        name: tonic-pyml-service
        volumeMounts: 
          - name: tmp
            mountPath: /tmp
          - name: var-log-nginx
            mountPath: /var/log/nginx
          - name: var-log-superd
            mountPath: /var/log/supervisor
          - name: var-run-nginx
            mountPath: /var/run/nginx
          - name: var-run-superd
            mountPath: /var/run/supervisor
          - name: var-cache-nginx
            mountPath: /var/cache/nginx
          - name: vector
            mountPath: /tonic/vector_data
          - name: public-log
            mountPath: /publish/logs_public
          - name: log
            mountPath: /publish/logs
        ports:
        - containerPort: 7700
        resources:
          limits:
            memory: "1Gi"
            {{- if ((.Values.resources).pyml_gpu).amount }}
            nvidia.com/gpu: {{ .Values.resources.pyml_gpu.amount }}
            {{- end }}
          requests:
            memory: "512Mi"
            ephemeral-storage: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7700
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7700
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      imagePullSecrets:
      - name: tonicai-build-writer-pull-secret
      serviceAccountName: {{ template "tonic.serviceAccountName" . }}
      volumes:
        - name: public-log
          emptyDir: {}
        - name: var-run-nginx
          emptyDir: {}
        - name: var-run-superd
          emptyDir: {}
        - name: var-log-nginx
          emptyDir: {}
        - name: var-log-superd
          emptyDir: {}
        - name: vector
          emptyDir: {}
        - name: var-cache-nginx
          emptyDir: {}
        - name: log
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      tolerations:
      {{- if (and (((.Values.resources).pyml_gpu).tolerations) (((.Values.resources).pyml_gpu).amount)) -}}
      {{ toYaml .Values.resources.pyml_gpu.tolerations | nindent 8 }}
      {{- end }}
