---
defaults:
  # Docker credentials
  - key: TONIC_DOCKER_CONFIG_JSON
    value: $secrets.rsm.TONIC_DOCKER_CONFIG_JSON
    secret: true

  # Database envs
  - key: TONIC_DB_PASS
    value: $secrets.rsm.TONIC_DB_PASS
    secret: true
  - key: TONIC_DB_HOST
    value: $secrets.rsm.TONIC_DB_HOST
    secret: true
  - key: TONIC_DB_USER
    value: postgres

  # Admin emails. Comma separated
  - key: TONIC_ADMIN_EMAILS
    value: $secrets.rsm.TONIC_ADMIN_EMAILS
    secret: true

  - key: TONIC_ENV_NAME
    value: releasehub

  - key: TONIC_LICENSE
    value: $secrets.rsm.TONIC_LICENSE
    secret: true
services: {}
mapping: {}
